// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentRemover
{
    internal sealed partial class Vsix
    {
        public const string Id = "CommentRemover.6fd99e75-71cb-45e4-a680-2723e4b0ec33";
        public const string Name = "CommentRemover";
        public const string Description = @"Code Comment Cleaner is a Visual Studio extension that helps you remove comments from your code quickly and easily. It supports removing single-line (//), multi-line (/* */), and XML documentation (///) comments.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
